# Generated by Django 4.1 on 2022-09-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_alter_marca_estado_alter_producto_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto_imagen',
            name='producto',
        ),
        migrations.AddField(
            model_name='categoria_producto',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria_producto',
            name='codigo',
            field=models.CharField(max_length=6),
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Producto_imagen',
        ),
    ]
