# Generated by Django 4.1 on 2022-09-16 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_remove_producto_imagen_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=250)),
                ('stock', models.IntegerField(default=0)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=4)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=4)),
                ('estado', models.SmallIntegerField(default=1, max_length=1)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.categoria_producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.proveedor_marca')),
            ],
        ),
        migrations.CreateModel(
            name='Producto_imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, upload_to='fotos/productos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
        ),
    ]
