# Generated by Django 4.1 on 2022-09-16 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0008_alter_producto_imagen_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto_imagen',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='producto.producto'),
        ),
    ]
